import type { Metadata } from "next";
import { Ropa_Sans } from "next/font/google";
import { ReduxProvider } from "@/app/redux/provider";

const ropa_sans = Ropa_Sans({
  subsets: ["latin"],
  weight: "400",
  style: "italic",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <div className="w-full h-full flex flex-col items-center justify-center">
      <div
        className={`${ropa_sans.className} w-full h-full flex flex-col items-center justify-center`}
      >
        <ReduxProvider>{children}</ReduxProvider>
      </div>
    </div>
  );
}
