import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Ropa_Sans } from "next/font/google";
import "./globals.css";
import { ReduxProvider } from "./redux/provider";

const ropa_sans = Ropa_Sans({
  subsets: ["latin"],
  weight: "400",
  style: "italic",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="w-full h-full">
      <body className={`${ropa_sans.className} w-full h-full`}>
        <div className="h-full">
          <ReduxProvider>{children}</ReduxProvider>
        </div>
      </body>
    </html>
  );
}
